# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.ohmyzsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#export ZSH_THEME="fishy"
export ZSH_THEME="fishy-mod"
#export ZSH_THEME="blinks-mod"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# added by denis: fzf plugin options
FZF_BASE=$(find /home/linuxbrew/.linuxbrew/Cellar/fzf -type d -regextype sed -regex '.*[0-9]\+\.[0-9]\+\.[0-9]\+')
# added by denis: colorize plugin option
#export ZSH_COLORIZE_STYLE="colorful"
export ZSH_COLORIZE_STYLE="material"
# export ZSH_COLORIZE_STYLE="solarized-dark"
# export ZSH_COLORIZE_STYLE="nord-darker"


# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(save-tilde zkbd git deb command-not-found debian gem rails zsh-syntax-highlighting dircycle vim)
#plugins=(save-tilde zkbd git deb command-not-found debian zsh-syntax-highlighting dircycle)
#plugins=(zkbd git command-not-found debian zsh-syntax-highlighting ripgrep fzf vim colored-man-pages colorize)
# plugins=(zkbd git-prompt command-not-found debian zsh-syntax-highlighting ripgrep fzf vim colorize)
plugins=(zkbd git-prompt command-not-found debian zsh-syntax-highlighting fzf vim colorize)
# plugins=(zkbd git command-not-found debian zsh-syntax-highlighting ripgrep fzf vim colorize)
#plugins=(zkbd command-not-found debian zsh-syntax-highlighting ripgrep fzf vim colorize colored-man-pages)

source $ZSH/ohmyzsh.sh

# Customize to your needs...

# the default connect for virsh
export VIRSH_DEFAULT_CONNECT_URI="qemu:///system"

# Bash Style Backward Kill via
# http://stackoverflow.com/questions/444951/zsh-stop-backward-kill-word-on-directory-delimiter?rq=1
export WORDCHARS='*?_-.[]~=/&;:!#$%^(){}<>'

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh # added by fzf

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=("$HOME/.juliaup/bin" $path)
export PATH

# <<< juliaup initialize <<<
